version: 2

jobs:
  version: 2

jobs:
  macos:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test --filter "RoutingKitTests.RouterTests"
  macos-release:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run: swift build -c release
  bionic:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build
      - run: swift test --filter "RoutingKitTests.RouterTests"
  bionic-release:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build -c release
  xenial:
    docker:
      - image: swift:5.0-xenial
    steps:
      - checkout
      - run: swift build
      - run: swift test --filter "RoutingKitTests.RouterTests"
  xenial-release:
    docker:
      - image: swift:5.0-xenial
    steps:
      - checkout
      - run: swift build -c release
  linux-performance:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run:
          name: swift test
          command: swift test -c release --filter "RoutingKitTests.RouterPerformanceTests"
workflows:
  version: 2
  tests:
    jobs:
      - macos
      - macos-release
      - bionic
      - bionic-release
      - xenial
      - xenial-release
notify:
  webhooks:
    - url: https://bot-gh.vapor.codes/circle/result
